package main

import (
	"log"
	"net/http"

	"dvorfs-repository-manager/internal/auth"
	"dvorfs-repository-manager/internal/cleanup"
	"dvorfs-repository-manager/internal/repository"
	"dvorfs-repository-manager/internal/user"
	"dvorfs-repository-manager/pkg/api"
	"dvorfs-repository-manager/pkg/database"

	_ "dvorfs-repository-manager/docs" // docs is generated by Swag CLI
)

// @title Dvorfs Repository Manager API
// @version 1.0
// @description This is the API for the Dvorfs Repository Manager.
// @contact.name API Support
// @contact.url http://www.dvorfs.com/support
// @contact.email support@dvorfs.com
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /api/v1
func main() {
	database.Connect()
	database.Migrate()

	// Initialize services
	authService := auth.NewService()
	repoService := repository.NewService()
	userService := user.NewService()
	cleanupService := cleanup.NewService()
	blobService := repository.NewBlobService(database.DB)

	// Initialize handlers
	authHandler := auth.NewHandler(authService)
	repoHandler := repository.NewHandler(repoService)
	userHandler := user.NewHandler(userService)
	cleanupHandler := cleanup.NewHandler(cleanupService)
	blobHandler := repository.NewBlobHandler(blobService)

	// Initialize router
	router := api.NewRouter(authHandler, repoHandler, userHandler, cleanupHandler, blobHandler)

	log.Println("Starting server on :8080")
	if err := http.ListenAndServe(":8080", router); err != nil {
		log.Fatal(err)
	}
}
